language: java

jdk: openjdk8

install:
  - ./gradlew clean jar

scripts:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - ./gradlew test jacocoTestCoverageVerification

deploy:
  - provider: script
    script: echo 'WTP'
    on:
      all_branches: true