language: java

jdk: openjdk8

install:
  - ./gradlew clean jar

stages:
  - test-jdk-8
  - test-jdk-9

jobs:
  include:
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/ui check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/cart check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/user check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/order check
      env:
        - COVERAGE=0.39
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/cart check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/product check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/user check
      env:
        - COVERAGE=0.31

    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/ui check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/cart check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-8
      jdk: openjdk8
      name: "jdk8-tests"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/service/user check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/order check
      env:
        - COVERAGE=0.36
    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/cart check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/product check
      env:
        - COVERAGE=0.5
    - stage: test-jdk-9
      jdk: oraclejdk9
      name: "jdk9-test"
      install: skip
      script:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/repository/user check
      env:
        - COVERAGE=0.31
    
after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  - provider: script
    script: echo 'WTP'
    on:
      all_branches: true